# TechX - Machine Learning Course 

## Assignment 1 - Python and NumPy

In [1]:
def test_function(function, test_cases, test_cases_answers):
    """Runs function through test cases"""
    passed = True
    
    for (case, answer) in zip(test_cases, test_cases_answers):
        output = function(case)
        if output != answer: 
            print('Your output: ', output, '\t Expected output: ', answer)
            passed = False
    
    if passed: 
        print('Test passed.')
    else: 
        print('Test failed.')

## Functions

###### 1) Write a function that calculates the average of an array in an iterative way

In [2]:
def average(array):
    """ Calculates the average of array. Returns average float"""
    
    #=============== YOUR CODE HERE ===================
    sum = 0
    for i in array:
        sum += i
    return sum/len(array)

Run the next cell to test your function.

In [3]:
test_cases_average = [[1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              [0.21780088, 0.4118428,  0.62573827, 0.78184048, 0.96162729, 0.21242742, 0.06843751, 0.70688805, 0.98459559, 0.1153083 ]]

test_cases_answers_average = [1, 5.5, 0.508650659]

test_function(average, test_cases_average, test_cases_answers_average)

Test passed.


### Indexing, Slicing and Iterating

###### 2) Extract the username of these emails. Beware, there may be different domains! You want to return the String before '@'.

Example: <br>
<b>input:</b> 'john.smith@qq.com' <br>
<b>return:</b>'john.smith'

<b>input:</b> 'jennifer@outlook.com' <br>
<b>return:</b>'jennifer' 

In [4]:
def extract_username(email): 
    """Extracts the username from the input email address. Return username String"""
    
    #=============== YOUR CODE HERE ===================
    for i in range(len(email)): 
        if (email[i] == '@'): 
            # Return String slice before '@'
            return email[:i]
    
    # Edge case: in case it is not an email. Return the whole String 
    # (@ is not part of the input String)
    return email

Run the next cell to test your function.

In [5]:
test_cases_extract_username = ['john-smith@gmail.com',
              'this.is.the.username@abcdefghijklmnopqrstuvwxyz',
              'invalid-email']

test_cases_answers_extract_username = ['john-smith', 'this.is.the.username', 'invalid-email']

test_function(extract_username, test_cases_extract_username, test_cases_answers_extract_username) 

Test passed.


<hr>

### Complete the following questions using ONLY NumPy

### Linear algebra operations 

###### 3) Import NumPy Library into your Python environment

In [6]:
#=============== YOUR CODE HERE ===================
import numpy as np

###### 4) Create a 10 element vector, x, of random integers between 10 and 15 (inclusive).  

In [7]:
x = np.random.randint(10, 16, size=10) # YOUR CODE HERE
print(x)

[12 11 10 15 14 15 15 13 13 12]


###### q) Print out the max value of the array. 

###### q) Print out the position of the max value of the array. 

###### 5) Create a 10 element vector, y, of 1.  

In [8]:
y = np.ones(10) # YOUR CODE HERE
print(y)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


###### 6) Add x and y together

In [9]:
answer = x + y # YOUR CODE HERE
print(answer)

[13. 12. 11. 16. 15. 16. 16. 14. 14. 13.]


###### 7) Convert the following matrix into a numpy array. 

$\begin{bmatrix}
5 & 10 & 15\\ 
2 &  13 & 23
\end{bmatrix}$

In [10]:
matrix = np.array([[5, 10, 15], 
                   [2, 13, 23]]) # YOUR CODE HERE

print(matrix)

[[ 5 10 15]
 [ 2 13 23]]


###### 8) Transpose the matrix. You should get 

$\begin{bmatrix}
5 & 2 \\
10 & 13 \\
15 & 23 \\
\end{bmatrix}$

In [11]:
matrix_T = matrix.T # YOUR CODE HERE
print(matrix_T)

[[ 5  2]
 [10 13]
 [15 23]]


###### 9) Multiply matrix and matrix_T together. You should get 

$\begin{bmatrix}
350 & 485 \\
485 & 702 
\end{bmatrix}$

In [12]:
matrix_square = np.dot(matrix, matrix_T) # YOUR CODE HERE
print(matrix_square)

[[350 485]
 [485 702]]


###### q) Print out the determinant of the squared matrix. 

In [45]:
det = np.linalg.det(matrix_square) # YOUR CODE HERE
print(det)

10474.99999999999


###### q) Print out the inverse matrix. 

In [46]:
inv = np.linalg.inv(matrix_square) # YOUR CODE HERE
print(inv)

[[ 0.06701671 -0.04630072]
 [-0.04630072  0.03341289]]


###### q) Print out the eigenvectors and the eigenvalues of the squared matrix. 

In [48]:
eigenvalues ,eigenvectors = np.linalg.eig(matrix_square) # YOUR CODE HERE
print('eigenvalues: ', eigenvalues)
print('eigenvectors: ', eigenvectors)

eigenvalues:  [  10.05329733 1041.94670267]
eigenvectors:  [[-0.81887743 -0.57396842]
 [ 0.57396842 -0.81887743]]


###### q) Check if the eigen properties hold true. 

Remember that the linear transformation by a matrix on its eigenvectors does not change the direction of the vector, only their lenghts. Eigenvalues are the scalars used to 'stretch' the eigenvectors during the transformation. 

$ Av = \lambda v $ 

In [49]:
# YOUR CODE HERE 

###### 10) Create a 3-element vector with integers of your choice. 

In [13]:
v = np.array([1, 2, 3]) # YOUR CODE HERE

###### 11) Multiply matrix and v. 
Be careful, you want to make sure that the dimensions of the two arrays match up. Your vector should therefore be a (3, 1) matrix. Use the <b>shape<b> to see what dimension is <emph>v<emph> and <b>reshape<b> as needed. 

In [14]:
v_reshaped = v.reshape((3, 1))
answer = np.dot(matrix, v_reshaped) # YOUR CODE HERE
print(answer)

[[70]
 [97]]


###### 12) Flatten matrix into a 6-element vector. 

In [15]:
flatten = matrix.flatten() # YOUR CODE HERE 
print(flatten)

[ 5 10 15  2 13 23]


###### 13) Concatenate the following matrices.

*Note: Don't forget to convert the matrices to numpy arrays first.*

In [42]:
matrix1 = [[1, 2, 3, 4, 5], 
           [6, 7, 8, 9, 10], 
           [11, 12, 13, 14, 15]]

matrix2 = [[16, 17, 18, 19, 20],
           [21, 22, 23, 24, 25],
           [26, 27, 28, 29, 30]]

a) along axis 0. 
You should get 

$\begin{bmatrix}
 1 & 2 & 3 & 4 & 5 \\
 6 & 7 & 8 & 9 & 10 \\
 11 & 12 & 13 & 14 & 15 \\
 16 & 17 & 18 & 19 & 20 \\
 21 & 22 & 23 & 24 & 25 \\
 26 & 27 & 28 & 29 & 30
\end{bmatrix}$

In [43]:
answer = np.concatenate((matrix1, matrix2),axis = 0) # YOUR CODE HERE 

print(answer)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


b) along axis 1. You should get

$\begin{bmatrix}
 1 & 2 & 3 & 4 & 5 & 16 & 17 & 18 & 19 & 20 \\
 6 & 7 & 8 & 9 & 10 & 21 & 22 & 23 & 24 & 25 \\
 11 & 12 & 13 & 14 & 15 & 26 & 27 & 28 & 29 & 30
\end{bmatrix}$

In [44]:
answer = np.concatenate((matrix1, matrix2),axis = 1) # YOUR CODE HERE 

print(answer)

[[ 1  2  3  4  5 16 17 18 19 20]
 [ 6  7  8  9 10 21 22 23 24 25]
 [11 12 13 14 15 26 27 28 29 30]]


### Basic statistics 

In [50]:
v = np.random.randint(20, size=30)
print(v)

[ 3 13  3  6  3  4  4 14 12  2 16  6 11 14 17 14 17  8  6 15  1 15  4  1
 17 14 14 10  8  4]


###### Print out the median of the list $ v $.

In [33]:
median = np.median(v) #=============== YOUR CODE HERE ===================
print(median)

6.0


###### Print out the standard deviation of $ v$.

In [52]:
std = np.std(v) # YOUR CODE HERE
print(std)

5.418486873657627


###### q) Randomly sample 5 items from the following list.

In [54]:
list = np.arange(10)
print(list)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
sample = np.random.choice(list, 5) # YOUR CODE HERE 
print(sample)

[8 0 1 8 0]


###### q) Now sample 5 items again from the list, but this time without replacement. 
If you are sampling with replacement, after each sampling, the item you chose is put into the pool and can be chosen again in following samplings. Whereas, the items are removed from the pool and will not be available again if you are not sampling with replacement. 

In [59]:
sample = np.random.choice(list, 5, replace=False) # YOUR CODE HERE 
print(sample)

[6 7 2 9 5]


### Now it is time for a (small) challenge 

###### Maximum A Posteriori 
At a very high level, in Bayesian statistics, MAP is an estimate of an unknown quantity that takes into considerations prior assumptions and past events. 
For example, in a coin toss, the theoretical assumption is 0.5 probability of face and tail. However, the probability distribution will change based on the previous results of the coin toss.

Let $x$ be the random variable of the coin toss, with $x$ = 1 being Head and $x$ = 0 Tail. Let $\theta$ be the probability of getting 1. Intuitively, suppose you get 3 heads out of 10 tosses, your $\theta$ value would be $\theta = \frac{head}{total} = \frac{3}{10} = 0.3$.


We can model the coin toss with a Bernouilli equation. 
$\theta = P(x = 1) = 1 - P(x = 0)$. 

The probability mass function of $x$ depending on $\theta$ is then $P(x | \theta) = \theta^x (1 - \theta)^{1-x}$, where $\theta$ is defined by prior data and updated after each iteration. 



The formula to estimate the probability is $ \hat{\theta}_{MAP}(x) = \underset{\theta}{\mathrm{argmin}} P(x | \theta) P(\theta)$

You can read more about MAP here: https://wiseodd.github.io/techblog/2017/01/01/mle-vs-map/


###### Given this, code out a formula that estimates the probability of a BIASED coin landing on HEAD after 20 tosses. 

Assume that you did not know that coin was biased at the beginning, so start with a $P(x = 1) = 0.5$. 
Toss your coin with a bias of $P(x = 1) = 0.8$. After each iteration, print out the total number of Tails and Heads you have gotten, and the updated $\theta$. 

What do you observe? 

