# Numpy Demo

In [2]:
import numpy as np

Create numpy array from regular numpy array. 

In [7]:
arr = [1, 2, 3, 4, 5]
numpy_array = np.array(arr)

print(type(arr))
print(type(numpy_array))
print(numpy_array)

matrix = [[1, 2, 3], 
         [4, 5, 6], 
         [7, 8, 9]]

np_matrix = np.array(matrix)
print(np_matrix)
print(np_matrix[2][:2])

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8]


Transpose matrix 

In [8]:
matrix_t = np_matrix.T
print(np_matrix)
print()
print(matrix_t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Addition: m+m

In [9]:
# numpy arrays
np_add = np_matrix + np_matrix
print(np_add)

# normal python array
add = matrix + matrix
print(add)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]


Average of the matrix 

In [11]:
avg = np.mean(np_matrix)
print(avg)

5.0


Sum of the matrix

In [12]:
summation = np.sum(np_matrix)
print(summation)

45


Min of the matrix and max of the matrix

In [13]:
minimum = np.min(np_matrix)
maximum = np.max(np_matrix)

print(minimum)
print(maximum)

1
9


Shape of the matrix

In [19]:
print(np_matrix)
print(np_matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


Reshape the matrix

In [16]:
flattened_matrix = np_matrix.flatten()
print(flattened_matrix)
print(flattened_matrix.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


In [18]:
reshaped = np_matrix.reshape((3, 3, 1))
print(reshaped)
print(reshaped.shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)
